version: "3.9"
services:
    web:
        build:
            context: 'https://github.com/cosic196/NetGrossVatApi.git'
            dockerfile: WebApi/Dockerfile
        ports:
            - "5000:5000"